// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package coupon

import (
	"context"
	"fmt"
)

type BaseResp struct {
	Code int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResp) SetCode(val int32) {
	p.Code = val
}
func (p *BaseResp) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "code",
	2: "msg",
}

type EmptyReq struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewEmptyReq() *EmptyReq {
	return &EmptyReq{}
}

func (p *EmptyReq) InitDefault() {
}

func (p *EmptyReq) GetId() (v int64) {
	return p.Id
}
func (p *EmptyReq) SetId(val int64) {
	p.Id = val
}

func (p *EmptyReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmptyReq(%+v)", *p)
}

var fieldIDToName_EmptyReq = map[int16]string{
	1: "id",
}

type CouponService interface {
	Test(ctx context.Context, req *EmptyReq) (r *BaseResp, err error)
}

type CouponServiceTestArgs struct {
	Req *EmptyReq `thrift:"req,1" frugal:"1,default,EmptyReq" json:"req"`
}

func NewCouponServiceTestArgs() *CouponServiceTestArgs {
	return &CouponServiceTestArgs{}
}

func (p *CouponServiceTestArgs) InitDefault() {
}

var CouponServiceTestArgs_Req_DEFAULT *EmptyReq

func (p *CouponServiceTestArgs) GetReq() (v *EmptyReq) {
	if !p.IsSetReq() {
		return CouponServiceTestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CouponServiceTestArgs) SetReq(val *EmptyReq) {
	p.Req = val
}

func (p *CouponServiceTestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CouponServiceTestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceTestArgs(%+v)", *p)
}

var fieldIDToName_CouponServiceTestArgs = map[int16]string{
	1: "req",
}

type CouponServiceTestResult struct {
	Success *BaseResp `thrift:"success,0,optional" frugal:"0,optional,BaseResp" json:"success,omitempty"`
}

func NewCouponServiceTestResult() *CouponServiceTestResult {
	return &CouponServiceTestResult{}
}

func (p *CouponServiceTestResult) InitDefault() {
}

var CouponServiceTestResult_Success_DEFAULT *BaseResp

func (p *CouponServiceTestResult) GetSuccess() (v *BaseResp) {
	if !p.IsSetSuccess() {
		return CouponServiceTestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CouponServiceTestResult) SetSuccess(x interface{}) {
	p.Success = x.(*BaseResp)
}

func (p *CouponServiceTestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CouponServiceTestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CouponServiceTestResult(%+v)", *p)
}

var fieldIDToName_CouponServiceTestResult = map[int16]string{
	0: "success",
}

