// Code generated by Kitex v0.15.4. DO NOT EDIT.

package couponservice

import (
	"context"
	coupon "example_shop/kitex_gen/coupon"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Test(ctx context.Context, req *coupon.EmptyReq, callOptions ...callopt.Option) (r *coupon.BaseResp, err error)
	SpotList(ctx context.Context, req *coupon.SpotListReq, callOptions ...callopt.Option) (r *coupon.SpotListResp, err error)
	SpotDetail(ctx context.Context, req *coupon.SpotDetailReq, callOptions ...callopt.Option) (r *coupon.SpotDetailResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCouponServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCouponServiceClient struct {
	*kClient
}

func (p *kCouponServiceClient) Test(ctx context.Context, req *coupon.EmptyReq, callOptions ...callopt.Option) (r *coupon.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Test(ctx, req)
}

func (p *kCouponServiceClient) SpotList(ctx context.Context, req *coupon.SpotListReq, callOptions ...callopt.Option) (r *coupon.SpotListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SpotList(ctx, req)
}

func (p *kCouponServiceClient) SpotDetail(ctx context.Context, req *coupon.SpotDetailReq, callOptions ...callopt.Option) (r *coupon.SpotDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SpotDetail(ctx, req)
}
