// Code generated by Kitex v0.15.4. DO NOT EDIT.

package couponservice

import (
	"context"
	"errors"
	coupon "example_shop/kitex_gen/coupon"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Test": kitex.NewMethodInfo(
		testHandler,
		newCouponServiceTestArgs,
		newCouponServiceTestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SpotList": kitex.NewMethodInfo(
		spotListHandler,
		newCouponServiceSpotListArgs,
		newCouponServiceSpotListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SpotDetail": kitex.NewMethodInfo(
		spotDetailHandler,
		newCouponServiceSpotDetailArgs,
		newCouponServiceSpotDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	couponServiceServiceInfo                = NewServiceInfo()
	couponServiceServiceInfoForClient       = NewServiceInfoForClient()
	couponServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return couponServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return couponServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return couponServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CouponService"
	handlerType := (*coupon.CouponService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "coupon",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func testHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceTestArgs)
	realResult := result.(*coupon.CouponServiceTestResult)
	success, err := handler.(coupon.CouponService).Test(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceTestArgs() interface{} {
	return coupon.NewCouponServiceTestArgs()
}

func newCouponServiceTestResult() interface{} {
	return coupon.NewCouponServiceTestResult()
}

func spotListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceSpotListArgs)
	realResult := result.(*coupon.CouponServiceSpotListResult)
	success, err := handler.(coupon.CouponService).SpotList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceSpotListArgs() interface{} {
	return coupon.NewCouponServiceSpotListArgs()
}

func newCouponServiceSpotListResult() interface{} {
	return coupon.NewCouponServiceSpotListResult()
}

func spotDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*coupon.CouponServiceSpotDetailArgs)
	realResult := result.(*coupon.CouponServiceSpotDetailResult)
	success, err := handler.(coupon.CouponService).SpotDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCouponServiceSpotDetailArgs() interface{} {
	return coupon.NewCouponServiceSpotDetailArgs()
}

func newCouponServiceSpotDetailResult() interface{} {
	return coupon.NewCouponServiceSpotDetailResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Test(ctx context.Context, req *coupon.EmptyReq) (r *coupon.BaseResp, err error) {
	var _args coupon.CouponServiceTestArgs
	_args.Req = req
	var _result coupon.CouponServiceTestResult
	if err = p.c.Call(ctx, "Test", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SpotList(ctx context.Context, req *coupon.SpotListReq) (r *coupon.SpotListResp, err error) {
	var _args coupon.CouponServiceSpotListArgs
	_args.Req = req
	var _result coupon.CouponServiceSpotListResult
	if err = p.c.Call(ctx, "SpotList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SpotDetail(ctx context.Context, req *coupon.SpotDetailReq) (r *coupon.SpotDetailResp, err error) {
	var _args coupon.CouponServiceSpotDetailArgs
	_args.Req = req
	var _result coupon.CouponServiceSpotDetailResult
	if err = p.c.Call(ctx, "SpotDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
